env:
  datasets_folder: /media/uv/Data/workspace/tridi/embody-3d/datasets
  raw_datasets_folder: ""
  assets_folder: /media/uv/Data/workspace/tridi/assets
  experiments_folder: /media/uv/Data/workspace/tridi/experiments
  smpl_folder: /media/uv/Data/workspace/tridi/smplx/models
